//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Runner.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionLog
    {
        public int id { get; set; }
        public string Lotto { get; set; }
        public string CodiceArticolo { get; set; }
        public Nullable<int> TempoCiclo { get; set; }
        public Nullable<bool> Waste { get; set; }
    }
}
